// Alfabeto Original;
let AlfabetoOriginal = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

// Função que gera o AlfabetoClaro em AlfabetoCifrado, tudo feito a partir da tabela ascii;
function cifrarAlfabeto(key) {
  let cifrar = "";
  let arr = new Array(26).fill(0);

  // Loop que comeca a modifica o alfabeto caso a letra esteja no intervalo de A-Z;
  for (let i = 0; i < key.length; i++) {
    if (key[i] >= "A" && key[i] <= "Z") {
      // Checa se aquela letra ja ta no novo alfabeto, caso nao esteja, adiciona;
      if (arr[key.charCodeAt(i) - 65] == 0) {
        cifrar += key[i];
        arr[key.charCodeAt(i) - 65] = 1;
      }
    } else if (key[i] >= "a" && key[i] <= "z") {
      if (arr[key.charCodeAt(i) - 97] == 0) {
        cifrar += String.fromCharCode(key.charCodeAt(i) - 32);
        arr[key.charCodeAt(i) - 97] = 1;
      }
    }
  }

  // Loop que adiciona as letras que faltam no novo alfabeto;
  for (let i = 0; i < 26; i++) {
    if (arr[i] == 0) {
      arr[i] = 1;
      cifrar += String.fromCharCode(65 + i);
    }
  }
  return cifrar;
}

// Funcao que pega o alfabeto cifrado e cifra a mensagem a partir dele;
function CifrarMensagem(msg, encoded) {
  // Faz uma copia do alfabeto cifrado;
  let copia = new Map();
  for (let i = 0; i < encoded.length; i++) {
    copia[encoded[i]] = i;
  }

  let cifra = "";

  // Nesse loop começa a cifrar a mensagem, os espaços e caracteres especiais sao mantidos;
  for (let i = 0; i < msg.length; i++) {
    if (msg[i] >= "a" && msg[i] <= "z") {
      let pos = copia[msg.charCodeAt(i) - 32];
      cifra += AlfabetoOriginal[pos];
    } else if (msg[i] >= "A" && msg[i] <= "Z") {
      let pos = copia[msg[i]];
      cifra += AlfabetoOriginal[pos];
    } else {
      cifra += msg[i];
    }
  }
  return cifra;
}

let chave = "parallelepiped";
let cifrarALFABETO = cifrarAlfabeto(chave);

console.log("Alfabeto Cifrado : ", cifrarALFABETO);
console.log(cifrarALFABETO.length);

let TextoClaro = `THE STORY OF ALADDIN AND HIS MAGICAL LAMP
THERE ONCE LIVED, IN ONE OF THE LARGE AND RICH CITIES OF CHINA, A TAILOR, NAMED MUSTAPHA. HE WAS VERY POOR. HE COULD HARDLY, BY HIS DAILY LABOR, MAINTAIN HIMSELF AND HIS FAMILY, WHICH CONSISTED ONLY OF HIS WIFE AND A SON.
HIS SON, WHO WAS CALLED ALADDIN, WAS A VERY CARELESS AND IDLE FELLOW. HE WAS DISOBEDIENT TO HIS FATHER AND MOTHER, AND WOULD GO OUT EARLY IN THE MORNING AND STAY OUT ALL DAY, PLAYING IN THE STREETS AND PUBLIC PLACES WITH IDLE CHILDREN OF HIS OWN AGE.
WHEN HE WAS OLD ENOUGH TO LEARN A TRADE, HIS FATHER TOOK HIM INTO HIS OWN SHOP, AND TAUGHT HIM HOW TO USE HIS NEEDLE; BUT ALL HIS FATHER'S ENDEAVORS TO KEEP HIM TO HIS WORK WERE VAIN, FOR NO SOONER WAS HIS BACK TURNED THAN HE WAS GONE FOR THAT DAY. MUSTAPHA CHASTISED HIM; BUT ALADDIN WAS INCORRIGIBLE, AND HIS FATHER, TO HIS GREAT GRIEF, WAS FORCED TO ABANDON HIM TO HIS IDLENESS, AND WAS SO MUCH TROUBLED ABOUT HIM THAT HE FELL SICK AND DIED IN A FEW MONTHS.
ALADDIN, WHO WAS NOW NO LONGER RESTRAINED BY THE FEAR OF A FATHER, GAVE HIMSELF ENTIRELY OVER TO HIS IDLE HABITS, AND WAS NEVER OUT OF THE STREETS FROM HIS COMPANIONS. THIS COURSE HE FOLLOWED TILL HE WAS FIFTEEN YEARS OLD, WITHOUT GIVING HIS MIND TO ANY USEFUL PURSUIT, OR THE LEAST REFLECTION ON WHAT WOULD BECOME OF HIM. AS HE WAS ONE DAY PLAYING, ACCORDING TO CUSTOM, IN THE STREET WITH HIS EVIL ASSOCIATES, A STRANGER PASSING BY STOOD TO OBSERVE HIM.
THIS STRANGER WAS A SORCERER, KNOWN AS THE AFRICAN MAGICIAN, AS HE HAD BEEN BUT TWO DAYS ARRIVED FROM AFRICA, HIS NATIVE COUNTRY.
THE AFRICAN MAGICIAN, OBSERVING IN ALADDIN'S COUNTENANCE SOMETHING WHICH ASSURED HIM THAT HE WAS A FIT BOY FOR HIS PURPOSE, INQUIRED HIS NAME AND HISTORY OF SOME OF HIS COMPANIONS; AND WHEN HE HAD LEARNED ALL HE DESIRED TO KNOW, WENT UP TO HIM, AND TAKING HIM ASIDE FROM HIS COMRADES, SAID, "CHILD, WAS NOT YOUR FATHER CALLED MUSTAPHA THE TAILOR?" "YES, SIR," ANSWERED THE BOY; "BUT HE HAS BEEN DEAD A LONG TIME."
AT THESE WORDS THE AFRICAN MAGICIAN THREW HIS ARMS ABOUT ALADDIN'S NECK, AND KISSED HIM SEVERAL TIMES, WITH TEARS IN HIS EYES, AND SAID, "I AM YOUR UNCLE. YOUR WORTHY FATHER WAS MY OWN BROTHER. I KNEW YOU AT FIRST SIGHT; YOU ARE SO LIKE HIM.” THEN HE GAVE ALADDIN A HANDFUL OF SMALL MONEY, SAYING, "GO, MY SON, TO YOUR MOTHER, GIVE MY LOVE TO HER, AND TELL HER THAT I WILL VISIT HER TO-MORROW, THAT I MAY SEE WHERE MY GOOD BROTHER LIVED SO LONG, AND ENDED HIS DAYS."
ALADDIN RAN TO HIS MOTHER, OVERJOYED AT THE MONEY HIS UNCLE HAD GIVEN HIM. "MOTHER," SAID HE, "HAVE I AN UNCLE?" "NO, CHILD," REPLIED HIS MOTHER, "YOU HAVE NO UNCLE BY YOUR FATHER'S SIDE OR MINE." "I AM JUST NOW COME," SAID ALADDIN, "FROM A MAN WHO SAYS HE IS MY UNCLE AND MY FATHER'S BROTHER. HE CRIED AND KISSED ME WHEN I TOLD HIM MY FATHER WAS DEAD, AND GAVE ME MONEY, SENDING HIS LOVE TO YOU, AND PROMISING TO COME AND PAY YOU A VISIT, THAT HE MAY SEE THE HOUSE MY FATHER LIVED AND DIED IN." "INDEED, CHILD," REPLIED THE MOTHER, "YOUR FATHER HAD NO BROTHER, NOR HAVE YOU AN UNCLE."
THE NEXT DAY THE MAGICIAN FOUND ALADDIN PLAYING IN ANOTHER PART OF THE TOWN, AND EMBRACING HIM AS BEFORE, PUT TWO PIECES OF GOLD INTO HIS HAND, AND SAID TO HIM, “CARRY THIS, CHILD, TO YOUR MOTHER. TELL HER THAT I WILL COME AND SEE HER TO-NIGHT, AND BID HER GET US SOMETHING FOR SUPPER; BUT FIRST SHOW ME THE HOUSE WHERE YOU LIVE."
ALADDIN SHOWED THE AFRICAN MAGICIAN THE HOUSE, AND CARRIED THE TWO PIECES OF GOLD TO HIS MOTHER, WHO WENT OUT AND BOUGHT PROVISIONS; AND, CONSIDERING SHE WANTED VARIOUS UTENSILS, BORROWED THEM OF HER NEIGHBORS. SHE SPENT THE WHOLE DAY IN PREPARING THE SUPPER; AND AT NIGHT, WHEN IT WAS READY, SAID TO HER SON, “PERHAPS THE STRANGER KNOWS NOT HOW TO FIND OUR HOUSE; GO AND BRING HIM, IF YOU MEET WITH HIM."ALADDIN WAS JUST READY TO GO, WHEN THE MAGICIAN KNOCKED AT THE DOOR, AND CAME IN LOADED WITH WINE AND ALL SORTS OF FRUITS, WHICH HE BROUGHT FOR A DESSERT. AFTER HE HAD GIVEN WHAT HE BROUGHT INTO ALADDIN'S HANDS, HE SALUTED HIS MOTHER, AND DESIRED HER TO SHOW HIM THE PLACE WHERE HIS BROTHER MUSTAPHA USED TO SIT ON THE SOFA; AND WHEN SHE HAD DONE SO, HE FELL DOWN AND KISSED IT SEVERAL TIMES, CRYING OUT, WITH TEARS IN HIS EYES, "MY POOR BROTHER! HOW UNHAPPY AM I, NOT TO HAVE COME SOON ENOUGH TO GIVE YOU ONE LAST EMBRACE!" ALADDIN'S MOTHER DESIRED HIM TO SIT DOWN IN THE SAME PLACE, BUT HE DECLINED.
"NO," SAID HE, "I SHALL NOT DO THAT; BUT GIVE ME LEAVE TO SIT OPPOSITE TO IT, THAT, ALTHOUGH I SEE NOT THE MASTER OF A FAMILY SO DEAR TO ME, I MAY AT LEAST BEHOLD THE PLACE WHERE HE USED TO SIT."
WHEN THE MAGICIAN HAD MADE CHOICE OF A PLACE, AND SAT DOWN, HE BEGAN TO ENTER INTO DISCOURSE WITH ALADDIN'S MOTHER. "MY GOOD SISTER," SAID HE, "DO NOT BE SURPRISED AT YOUR NEVER HAVING SEEN ME ALL THE TIME YOU HAVE BEEN MARRIED TO MY BROTHER MUSTAPHA OF HAPPY MEMORY. I HAVE BEEN FORTY YEARS ABSENT FROM THIS COUNTRY, WHICH IS MY NATIVE PLACE, AS WELL AS MY LATE BROTHER'S; AND DURING THAT TIME HAVE TRAVELLED INTO THE INDIES, PERSIA, ARABIA, SYRIA, AND EGYPT, AND AFTERWARD CROSSED OVER INTO AFRICA, WHERE I TOOK UP MY ABODE. AT LAST, AS IT IS NATURAL FOR A MAN, I WAS DESIROUS TO SEE MY NATIVE COUNTRY AGAIN, AND TO EMBRACE MY DEAR BROTHER; AND FINDING I HAD STRENGTH ENOUGH TO UNDERTAKE SO LONG A JOURNEY, I MADE THE NECESSARY PREPARATIONS, AND SET OUT. NOTHING EVER AFFLICTED ME SO MUCH AS HEARING OF MY BROTHER'S DEATH. BUT GOD BE PRAISED FOR ALL THINGS! IT IS A COMFORT FOR ME TO FIND, AS IT WERE, MY BROTHER IN A SON WHO HAS HIS MOST REMARKABLE FEATURES."
`
console.log("Texto Cifrado : ", CifrarMensagem(TextoClaro, cifrarALFABETO));
let textocifra = CifrarMensagem(TextoClaro, cifrarALFABETO);

console.log(TextoClaro)
console.log(textocifra)

/* 
THE STORY OF ALADDIN AND HIS MAGICAL LAMP
THERE ONCE LIVED, IN ONE OF THE LARGE AND RICH CITIES OF CHINA, A TAILOR, NAMED MUSTAPHA. HE WAS VERY POOR. HE COULD HARDLY, BY HIS DAILY LABOR, MAINTAIN HIMSELF AND HIS FAMILY, WHICH CONSISTED ONLY OF HIS WIFE AND A SON.
HIS SON, WHO WAS CALLED ALADDIN, WAS A VERY CARELESS AND IDLE FELLOW. HE WAS DISOBEDIENT TO HIS FATHER AND MOTHER, AND WOULD GO OUT EARLY IN THE MORNING AND STAY OUT ALL DAY, PLAYING IN THE STREETS AND PUBLIC PLACES WITH IDLE CHILDREN OF HIS OWN AGE.
WHEN HE WAS OLD ENOUGH TO LEARN A TRADE, HIS FATHER TOOK HIM INTO HIS OWN SHOP, AND TAUGHT HIM HOW TO USE HIS NEEDLE; BUT ALL HIS FATHER’S ENDEAVORS TO KEEP HIM TO HIS WORK WERE VAIN, FOR NO SOONER WAS HIS BACK TURNED THAN HE WAS GONE FOR THAT DAY. MUSTAPHA CHASTISED HIM; BUT ALADDIN WAS INCORRIGIBLE, AND HIS FATHER, TO HIS GREAT GRIEF, WAS FORCED TO ABANDON HIM TO HIS IDLENESS, AND WAS SO MUCH TROUBLED ABOUT HIM THAT HE FELL SICK AND DIED IN A FEW MONTHS.
ALADDIN, WHO WAS NOW NO LONGER RESTRAINED BY THE FEAR OF A FATHER, GAVE HIMSELF ENTIRELY OVER TO HIS IDLE HABITS, AND WAS NEVER OUT OF THE STREETS FROM HIS COMPANIONS. THIS COURSE HE FOLLOWED TILL HE WAS FIFTEEN YEARS OLD, WITHOUT GIVING HIS MIND TO ANY USEFUL PURSUIT, OR THE LEAST REFLECTION ON WHAT WOULD BECOME OF HIM. AS HE WAS ONE DAY PLAYING, ACCORDING TO CUSTOM, IN THE STREET WITH HIS EVIL ASSOCIATES, A STRANGER PASSING BY STOOD TO OBSERVE HIM.
THIS STRANGER WAS A SORCERER, KNOWN AS THE AFRICAN MAGICIAN, AS HE HAD BEEN BUT TWO DAYS ARRIVED FROM AFRICA, HIS NATIVE COUNTRY.
THE AFRICAN MAGICIAN, OBSERVING IN ALADDIN’S COUNTENANCE SOMETHING WHICH ASSURED HIM THAT HE WAS A FIT BOY FOR HIS PURPOSE, INQUIRED HIS NAME AND HISTORY OF SOME OF HIS COMPANIONS; AND WHEN HE HAD LEARNED ALL HE DESIRED TO KNOW, WENT UP TO HIM, AND TAKING HIM ASIDE FROM HIS COMRADES, SAID, “CHILD, WAS NOT YOUR FATHER CALLED MUSTAPHA THE TAILOR?” “YES, SIR,” ANSWERED THE BOY; “BUT HE HAS BEEN DEAD A LONG TIME.”
AT THESE WORDS THE AFRICAN MAGICIAN THREW HIS ARMS ABOUT ALADDIN’S NECK, AND KISSED HIM SEVERAL TIMES, WITH TEARS IN HIS EYES, AND SAID, “I AM YOUR UNCLE. YOUR WORTHY FATHER WAS MY OWN BROTHER. I KNEW YOU AT FIRST SIGHT; YOU ARE SO LIKE HIM.” THEN HE GAVE ALADDIN A HANDFUL OF SMALL MONEY, SAYING, “GO, MY SON, TO YOUR MOTHER, GIVE MY LOVE TO HER, AND TELL HER THAT I WILL VISIT HER TO-MORROW, THAT I MAY SEE WHERE MY GOOD BROTHER LIVED SO LONG, AND ENDED HIS DAYS.”
ALADDIN RAN TO HIS MOTHER, OVERJOYED AT THE MONEY HIS UNCLE HAD GIVEN HIM. “MOTHER,” SAID HE, “HAVE I AN UNCLE?” “NO, CHILD,” REPLIED HIS MOTHER, “YOU HAVE NO UNCLE BY YOUR FATHER’S SIDE OR MINE.” “I AM JUST NOW COME,” SAID ALADDIN, “FROM A MAN WHO SAYS HE IS MY UNCLE AND MY FATHER’S BROTHER. HE CRIED AND KISSED ME WHEN I TOLD HIM MY FATHER WAS DEAD, AND GAVE ME MONEY, SENDING HIS LOVE TO YOU, AND PROMISING TO COME AND PAY YOU A VISIT, THAT HE MAY SEE THE HOUSE MY FATHER LIVED AND DIED IN.” “INDEED, CHILD,” REPLIED THE MOTHER, “YOUR FATHER HAD NO BROTHER, NOR HAVE YOU AN UNCLE.”
THE NEXT DAY THE MAGICIAN FOUND ALADDIN PLAYING IN ANOTHER PART OF THE TOWN, AND EMBRACING HIM AS BEFORE, PUT TWO PIECES OF GOLD INTO HIS HAND, AND SAID TO HIM, “CARRY THIS, CHILD, TO YOUR MOTHER. TELL HER THAT I WILL COME AND SEE HER TO-NIGHT, AND BID HER GET US SOMETHING FOR SUPPER; BUT FIRST SHOW ME THE HOUSE WHERE YOU LIVE.”
ALADDIN SHOWED THE AFRICAN MAGICIAN THE HOUSE, AND CARRIED THE TWO PIECES OF GOLD TO HIS MOTHER, WHO WENT OUT AND BOUGHT PROVISIONS; AND, CONSIDERING SHE WANTED VARIOUS UTENSILS, BORROWED THEM OF HER NEIGHBORS. SHE SPENT THE WHOLE DAY IN PREPARING THE SUPPER; AND AT NIGHT, WHEN IT WAS READY, SAID TO HER SON, “PERHAPS THE STRANGER KNOWS NOT HOW TO FIND OUR HOUSE; GO AND BRING HIM, IF YOU MEET WITH HIM.”ALADDIN WAS JUST READY TO GO, WHEN THE MAGICIAN KNOCKED AT THE DOOR, AND CAME IN LOADED WITH WINE AND ALL SORTS OF FRUITS, WHICH HE BROUGHT FOR A DESSERT. AFTER HE HAD GIVEN WHAT HE BROUGHT INTO ALADDIN’S HANDS, HE SALUTED HIS MOTHER, AND DESIRED HER TO SHOW HIM THE PLACE WHERE HIS BROTHER MUSTAPHA USED TO SIT ON THE SOFA; AND WHEN SHE HAD DONE SO, HE FELL DOWN AND KISSED IT SEVERAL TIMES, CRYING OUT, WITH TEARS IN HIS EYES, “MY POOR BROTHER! HOW UNHAPPY AM I, NOT TO HAVE COME SOON ENOUGH TO GIVE YOU ONE LAST EMBRACE!” ALADDIN’S MOTHER DESIRED HIM TO SIT DOWN IN THE SAME PLACE, BUT HE DECLINED.
“NO,” SAID HE, “I SHALL NOT DO THAT; BUT GIVE ME LEAVE TO SIT OPPOSITE TO IT, THAT, ALTHOUGH I SEE NOT THE MASTER OF A FAMILY SO DEAR TO ME, I MAY AT LEAST BEHOLD THE PLACE WHERE HE USED TO SIT.”
WHEN THE MAGICIAN HAD MADE CHOICE OF A PLACE, AND SAT DOWN, HE BEGAN TO ENTER INTO DISCOURSE WITH ALADDIN’S MOTHER. “MY GOOD SISTER,” SAID HE, “DO NOT BE SURPRISED AT YOUR NEVER HAVING SEEN ME ALL THE TIME YOU HAVE BEEN MARRIED TO MY BROTHER MUSTAPHA OF HAPPY MEMORY. I HAVE BEEN FORTY YEARS ABSENT FROM THIS COUNTRY, WHICH IS MY NATIVE PLACE, AS WELL AS MY LATE BROTHER’S; AND DURING THAT TIME HAVE TRAVELLED INTO THE INDIES, PERSIA, ARABIA, SYRIA, AND EGYPT, AND AFTERWARD CROSSED OVER INTO AFRICA, WHERE I TOOK UP MY ABODE. AT LAST, AS IT IS NATURAL FOR A MAN, I WAS DESIROUS TO SEE MY NATIVE COUNTRY AGAIN, AND TO EMBRACE MY DEAR BROTHER; AND FINDING I HAD STRENGTH ENOUGH TO UNDERTAKE SO LONG A JOURNEY, I MADE THE NECESSARY PREPARATIONS, AND SET OUT. NOTHING EVER AFFLICTED ME SO MUCH AS HEARING OF MY BROTHER’S DEATH. BUT GOD BE PRAISED FOR ALL THINGS! IT IS A COMFORT FOR ME TO FIND, AS IT WERE, MY BROTHER IN A SON WHO HAS HIS MOST REMARKABLE FEATURES.”
*/
